language: python
sudo: false
os:
    - linux
    ## - osx
python:
    - 2.7
before_install:
    ## # osx builders don't come with python
    ## - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install python; fi
    # Use miniconda for dependencies, pip is too slow -- https://gist.github.com/zonca/9958333
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda
    # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
    # - sudo rm -rf /dev/shm
    # - sudo ln -s /run/shm /dev/shm
install: 
    - conda create --yes -n testenv python=$TRAVIS_PYTHON_VERSION Cython numpy scipy h5py nose
    - source activate testenv
    - python setup.py build_ext --inplace
    - python setup.py install
script: 
    - nosetests
